export const interviewQuotes = [
  "'Success is not final, failure is not fatal: It is the courage to continue that counts.' – Winston Churchill",
  "'Believe you can and you're halfway there.' – Theodore Roosevelt",
  "'The only way to do great work is to love what you do.' – Steve Jobs",
  "'Your attitude, not your aptitude, will determine your altitude.' – Zig Ziglar",
  "'Preparation is the key to success.' – Alexander Graham Bell",
  "'The expert in anything was once a beginner.' – Helen Hayes",
  "'Don't be afraid to give up the good to go for the great.' – John D. Rockefeller",
  "'Opportunities don't happen, you create them.' – Chris Grosser",
  "'The future belongs to those who believe in the beauty of their dreams.' – Eleanor Roosevelt",
  "'Success is where preparation and opportunity meet.' – Bobby Unser",
  "'Your time is limited, don't waste it living someone else's life.' – Steve Jobs",
  "'Be yourself; everyone else is already taken.' – Oscar Wilde",
  "'The best way to predict the future is to create it.' – Peter Drucker",
  "'Confidence comes not from always being right but from not fearing to be wrong.' – Peter T. McIntyre",
  "'Every accomplishment starts with the decision to try.' – John F. Kennedy",
  "'You miss 100% of the shots you don't take.' – Wayne Gretzky",
  "'The only impossible journey is the one you never begin.' – Tony Robbins",
  "'Success is not the key to happiness. Happiness is the key to success.' – Albert Schweitzer",
  "'What lies behind us and what lies before us are tiny matters compared to what lies within us.' – Ralph Waldo Emerson",
  "'The difference between ordinary and extraordinary is that little extra.' – Jimmy Johnson",
  "'In the middle of every difficulty lies opportunity.' – Albert Einstein",
  "'You are never too old to set another goal or to dream a new dream.' – C.S. Lewis",
  "'The only limit to our realization of tomorrow will be our doubts of today.' – Franklin D. Roosevelt",
  "'A journey of a thousand miles begins with a single step.' – Lao Tzu",
  "'The harder you work for something, the greater you'll feel when you achieve it.' – Anonymous"
]